name: "🐛 Bug Report"
description: Report a reproducible problem or unexpected behavior
labels: [bug]
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: e.g. OS, browser, Node version, etc.
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes/Screenshots
      placeholder: Anything else to add?
