name: "🔒 Report a Security Vulnerability"
description: Privately disclose a security issue (do NOT post sensitive info publicly)
labels: [security]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Do not disclose sensitive details publicly.**
        Please email security@omni.dev for responsible disclosure.
        You can still submit high-level info below if needed.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Brief description of the potential vulnerability
  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      placeholder: What could an attacker do if this is exploited?
  - type: textarea
    id: reproduction
    attributes:
      label: Steps or Conditions
      placeholder: If safe to share, how can this be reproduced?
